// Other inclusions ...
#include "Reader.h"

void Reader::chooseValue(std::string value) {
  // ...
}
bool Reader::readNext() {
  // ...
}
unsigned Reader::getNumReals() const {
  // ...
}
unsigned Reader::getNumInts() const {
  // ...
}
unsigned Reader::getNumOthers() const {
  // ...
}
